MODELS_PATH: "./"
EXPS_PATH: "./checkpoints/output"

HFLICKR_PATH: "/home/dataset/IHD/HFlickr"
HDAY2NIGHT_PATH: "/home/dataset/IHD/Hday2night"
HCOCO_PATH: "/home/dataset/IHD/HCOCO"
HADOBE5K1_PATH: "/data/IHD/HAdobe5k"
HADOBE5K_PATH: "/home/dataset/IHD/HAdobe5k_resized1024"


IMAGENET_PRETRAINED_MODELS:
  HRNETV2_W18_SMALL: "./pretrained_models/hrnet_w18_small_model_v2.pth"
  HRNETV2_W18: "./pretrained_models/hrnetv2_w18_imagenet_pretrained.pth"
  HRNETV2_W32: "./pretrained_models/hrnetv2_w32_imagenet_pretrained.pth"
  HRNETV2_W40: "./pretrained_models/hrnetv2_w40_imagenet_pretrained.pth"
  HRNETV2_W48: "./pretrained_models/hrnetv2_w48_imagenet_pretrained.pth"
  HistNet: "./checkpoints/last_model/hen_train/last_checkpoint.pth"
#  HistNet_old: "./checkpoints/last_model/hen_train/last_checkpoint.pth"
